FROM node:20-alpine

RUN apk add --no-cache bash curl

WORKDIR /app

COPY app/package*.json ./

RUN npm install

COPY app/ .

RUN chown -R node:node /app

USER node

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]