services:


  vue:
    build:
      context: ./frontEnd
    container_name: vue_client
    ports:
      - "80:5173"
    volumes:
      - ./frontEnd/app:/app
      - /app/node_modules
    command: npm run dev -- --host






 
